### ISSUE TITLE
Error with python3.9

### ISSUE THREAD

**Issue by helioshk** [lazywalker/DigiSkimmer#5]
Hi,

Thanks for the great software. It runs well with python3.8.
Debian testing seems to have removed python3.8 support and DigiSkimmer now returns an error:

```
2020-12-07 23:33:02,216 ERROR 282401 [kiwi-80] KW Error
Traceback (most recent call last):
  File "./lib/kiwi/worker.py", line 38, in run
    self._recorder.open()
  File "./lib/kiwi/client.py", line 510, in open
    self._set_auth('kiwi', self._options.password, self._options.tlimit_password)
  File "./lib/kiwi/client.py", line 173, in _set_auth
    self._send_message('SET auth t=%s p=%s' % (client_type, password))
  File "./lib/kiwi/client.py", line 163, in _send_message
    self._stream.send_message(msg)
  File "./lib/mod_pywebsocket/_stream_hybi.py", line 523, in send_message
    self._write(self._writer.build(message, end, binary))
  File "./lib/mod_pywebsocket/_stream_hybi.py", line 343, in build
    return create_text_frame(
  File "./lib/mod_pywebsocket/_stream_hybi.py", line 165, in create_text_frame
    return create_binary_frame(encoded_message, opcode, fin, mask,
  File "./lib/mod_pywebsocket/_stream_hybi.py", line 157, in create_binary_frame
    return _filter_and_format_frame_object(frame, mask, frame_filters)
  File "./lib/mod_pywebsocket/_stream_hybi.py", line 149, in _filter_and_format_frame_object
    return _build_frame(header, frame.payload, mask)
  File "./lib/mod_pywebsocket/_stream_hybi.py", line 139, in _build_frame
    return header + masking_nonce + masker.mask(body)
  File "./lib/mod_pywebsocket/util.py", line 201, in _mask_using_array
    result.fromstring(bytes(s))
AttributeError: 'array.array' object has no attribute 'fromstring'
2020-12-07 23:33:02,217 ERROR 282401 [kiwi-80] websocket close: "'array.array' object has no attribute 'fromstring'"
```

73

**Comment by helioshk** [comment]
With the recent patches it seems to work using python3.9, many thanks!

**Comment by lazywalker** [comment]
glad it helps 👍

**Comment by helioshk** [comment]
I don't know if it is related to this change. Once or twice a day it stops uploading to pskreporter. Only when I stop it (ctrl-c), it uploads a batch of several thousand spots.

**Comment by lazywalker** [comment]
@helioshk is there a way to reproduce the issue? me at debian/testing latest update(with wsjtx 2.3.0-rc2), running 3 different sites with 39 channels simultaneously, all good for a week now. 

here's my settings:

```python
TMP_PATH = '/dev/shm/digiskr'
LOG_SPOTS = True
LOG_TO_FILE = True
DEBUG = False

DECODER_QUEUE = {
        'maxsize': 150,
        'workers': 4
     }

...
```

**Comment by helioshk** [comment]
It is not reproducible unfortunately and it hasn't happened anymore since 36 hours. I don't know if it is relevant, but my PC is slow and sometimes it can't complete decoding the queue in time. 
Once it is in the state where it doesn't upload to pskreporter anymore, there is no more message about attempts to upload, only the decoding continues.

I use the settings from the example file:
```
TMP_PATH = './tmp/digiskr/' 
LOG_PATH = './log/'
LOG_TO_FILE = False
LOG_SPOTS = False   

DECODER_QUEUE = {
    'maxsize': 10,
    'workers': 3
}
```

**Comment by lazywalker** [comment]
here is some tricks for machine that not good enough: 
- use mem-disk for tmp_path, this will increase io speed especially for old PC 
```python
TMP_PATH = '/dev/shm/digiskr'
```
- increasing the maxsize of queue with workers number decreased, will save some of your cpu cost
```python
DECODER_QUEUE = {
    'maxsize': 30,
    'workers': 2
}
```

**Comment by helioshk** [comment]
I think I can reproduce the issue.
If the internet connection is interrupted (I use WiFi) for a while, it will not resume uploading after internet access is available again.

**Comment by lazywalker** [comment]
> I think I can reproduce the issue.
> If the internet connection is interrupted (I use WiFi) for a while, it will not resume uploading after internet access is available again.

Thanks for the information, please referring to this issue #9
